### ISSUE TITLE
Extremely low frame rate

### ISSUE THREAD

**Issue by ngokevin** [MozVR/puzzle-rain#105]
Firefox Developer Edition 59, HTC Vive, GTX 1080.

**Comment by arturitu** [comment]
I was trying yesterday to increase the frame rate with the latest FF but I couldn't fit it, my first suspect was that it has a lot of drawcalls up to 135 aprox. but removing elements from the scene until I only had 30-35 drawcallls the low frame rate continues. I tried to remove shadows, lights but didn't work neither. I'll try to find out what might be going on. Sorry.

**Comment by ngokevin** [comment]
Thanks for checking it out, I'll also take a look when I can.

**Comment by ngokevin** [comment]
Seems like it's doing a lot of texture uploading (texImage2D) and setProgram. Is there somewhere a texture could be cached or not constantly recreated? What if we remove all the particle systems?

**Comment by arturitu** [comment]
One of the dumbest bugs I'd ever seen. Sorry, now is working smooth with my GeForce GTX 970.

**Comment by ngokevin** [comment]
Woot! Thanks @arturitu! Looks simple, but hard to find :)

**Comment by cvan** [comment]
many thanks! 👍
